### ISSUE TITLE
Mod The Gungeon Installer has an ERROR

### ISSUE THREAD

**Issue by shawnatiqur** [ModTheGungeon/ETGMod.Installer.Core#53]
This is the log:
ETGMod Installer v19.4.12
Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: UnityPlayer.dll
WARNING: Backup not found for UnityPlayer.dll
Reverting: Assembly-CSharp.dll
Reloading Assembly-CSharp.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Backing up: UnityPlayer.dll
System.IO.FileNotFoundException: Could not find file 'C:\Users\Farah Atiqur\Desktop\Game Folder\Enter.the.Gungeon.v1.1.4h3\UnityPlayer.dll'.
File name: 'C:\Users\Farah Atiqur\Desktop\Game Folder\Enter.the.Gungeon.v1.1.4h3\UnityPlayer.dll'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ETGModInstaller.ETGModder.BackupETG(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by shawnatiqur** [comment]
Please help me out.
